# Generated by Django 6.0.3 on 2026-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend Development'), ('FULLSTACK', 'Full Stack Development')], default='backend', max_length=20),
            preserve_default=False,
        ),
    ]
